/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminGateRouteImport } from './routes/admin-gate'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedUserRouteRouteImport } from './routes/_authenticated/user/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedUserIndexRouteImport } from './routes/_authenticated/user/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedUserUsageRouteImport } from './routes/_authenticated/user/usage'
import { Route as AuthenticatedUserOrdersRouteImport } from './routes/_authenticated/user/orders'
import { Route as AuthenticatedUserLicensesRouteImport } from './routes/_authenticated/user/licenses'
import { Route as AuthenticatedUserInstallRouteImport } from './routes/_authenticated/user/install'
import { Route as AuthenticatedUserAccountRouteImport } from './routes/_authenticated/user/account'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin/usage'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin/packages'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminLicensesRouteImport } from './routes/_authenticated/admin/licenses'
import { Route as AuthenticatedAdminLedgerRouteImport } from './routes/_authenticated/admin/ledger'

const AdminGateRoute = AdminGateRouteImport.update({
  id: '/admin-gate',
  path: '/admin-gate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserRouteRoute = AuthenticatedUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserIndexRoute = AuthenticatedUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUserRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedUserUsageRoute = AuthenticatedUserUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedUserRouteRoute,
} as any)
const AuthenticatedUserOrdersRoute = AuthenticatedUserOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedUserRouteRoute,
} as any)
const AuthenticatedUserLicensesRoute =
  AuthenticatedUserLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AuthenticatedUserRouteRoute,
  } as any)
const AuthenticatedUserInstallRoute =
  AuthenticatedUserInstallRouteImport.update({
    id: '/install',
    path: '/install',
    getParentRoute: () => AuthenticatedUserRouteRoute,
  } as any)
const AuthenticatedUserAccountRoute =
  AuthenticatedUserAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedUserRouteRoute,
  } as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLicensesRoute =
  AuthenticatedAdminLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLedgerRoute =
  AuthenticatedAdminLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/admin-gate': typeof AdminGateRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/user': typeof AuthenticatedUserRouteRouteWithChildren
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/user/account': typeof AuthenticatedUserAccountRoute
  '/user/install': typeof AuthenticatedUserInstallRoute
  '/user/licenses': typeof AuthenticatedUserLicensesRoute
  '/user/orders': typeof AuthenticatedUserOrdersRoute
  '/user/usage': typeof AuthenticatedUserUsageRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/user/': typeof AuthenticatedUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/admin-gate': typeof AdminGateRoute
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/user/account': typeof AuthenticatedUserAccountRoute
  '/user/install': typeof AuthenticatedUserInstallRoute
  '/user/licenses': typeof AuthenticatedUserLicensesRoute
  '/user/orders': typeof AuthenticatedUserOrdersRoute
  '/user/usage': typeof AuthenticatedUserUsageRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/user': typeof AuthenticatedUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-gate': typeof AdminGateRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/user': typeof AuthenticatedUserRouteRouteWithChildren
  '/_authenticated/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/_authenticated/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/user/account': typeof AuthenticatedUserAccountRoute
  '/_authenticated/user/install': typeof AuthenticatedUserInstallRoute
  '/_authenticated/user/licenses': typeof AuthenticatedUserLicensesRoute
  '/_authenticated/user/orders': typeof AuthenticatedUserOrdersRoute
  '/_authenticated/user/usage': typeof AuthenticatedUserUsageRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/user/': typeof AuthenticatedUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-gate'
    | '/admin'
    | '/user'
    | '/admin/ledger'
    | '/admin/licenses'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/usage'
    | '/user/account'
    | '/user/install'
    | '/user/licenses'
    | '/user/orders'
    | '/user/usage'
    | '/admin/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-gate'
    | '/admin/ledger'
    | '/admin/licenses'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/usage'
    | '/user/account'
    | '/user/install'
    | '/user/licenses'
    | '/user/orders'
    | '/user/usage'
    | '/admin'
    | '/user'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin-gate'
    | '/_authenticated/admin'
    | '/_authenticated/user'
    | '/_authenticated/admin/ledger'
    | '/_authenticated/admin/licenses'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/usage'
    | '/_authenticated/user/account'
    | '/_authenticated/user/install'
    | '/_authenticated/user/licenses'
    | '/_authenticated/user/orders'
    | '/_authenticated/user/usage'
    | '/_authenticated/admin/'
    | '/_authenticated/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminGateRoute: typeof AdminGateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin-gate': {
      id: '/admin-gate'
      path: '/admin-gate'
      fullPath: '/admin-gate'
      preLoaderRoute: typeof AdminGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user': {
      id: '/_authenticated/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthenticatedUserRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/': {
      id: '/_authenticated/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof AuthenticatedUserIndexRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/user/usage': {
      id: '/_authenticated/user/usage'
      path: '/usage'
      fullPath: '/user/usage'
      preLoaderRoute: typeof AuthenticatedUserUsageRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
    '/_authenticated/user/orders': {
      id: '/_authenticated/user/orders'
      path: '/orders'
      fullPath: '/user/orders'
      preLoaderRoute: typeof AuthenticatedUserOrdersRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
    '/_authenticated/user/licenses': {
      id: '/_authenticated/user/licenses'
      path: '/licenses'
      fullPath: '/user/licenses'
      preLoaderRoute: typeof AuthenticatedUserLicensesRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
    '/_authenticated/user/install': {
      id: '/_authenticated/user/install'
      path: '/install'
      fullPath: '/user/install'
      preLoaderRoute: typeof AuthenticatedUserInstallRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
    '/_authenticated/user/account': {
      id: '/_authenticated/user/account'
      path: '/account'
      fullPath: '/user/account'
      preLoaderRoute: typeof AuthenticatedUserAccountRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/licenses': {
      id: '/_authenticated/admin/licenses'
      path: '/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AuthenticatedAdminLicensesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ledger': {
      id: '/_authenticated/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AuthenticatedAdminLedgerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminLedgerRoute: typeof AuthenticatedAdminLedgerRoute
  AuthenticatedAdminLicensesRoute: typeof AuthenticatedAdminLicensesRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminLedgerRoute: AuthenticatedAdminLedgerRoute,
    AuthenticatedAdminLicensesRoute: AuthenticatedAdminLicensesRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedUserRouteRouteChildren {
  AuthenticatedUserAccountRoute: typeof AuthenticatedUserAccountRoute
  AuthenticatedUserInstallRoute: typeof AuthenticatedUserInstallRoute
  AuthenticatedUserLicensesRoute: typeof AuthenticatedUserLicensesRoute
  AuthenticatedUserOrdersRoute: typeof AuthenticatedUserOrdersRoute
  AuthenticatedUserUsageRoute: typeof AuthenticatedUserUsageRoute
  AuthenticatedUserIndexRoute: typeof AuthenticatedUserIndexRoute
}

const AuthenticatedUserRouteRouteChildren: AuthenticatedUserRouteRouteChildren =
  {
    AuthenticatedUserAccountRoute: AuthenticatedUserAccountRoute,
    AuthenticatedUserInstallRoute: AuthenticatedUserInstallRoute,
    AuthenticatedUserLicensesRoute: AuthenticatedUserLicensesRoute,
    AuthenticatedUserOrdersRoute: AuthenticatedUserOrdersRoute,
    AuthenticatedUserUsageRoute: AuthenticatedUserUsageRoute,
    AuthenticatedUserIndexRoute: AuthenticatedUserIndexRoute,
  }

const AuthenticatedUserRouteRouteWithChildren =
  AuthenticatedUserRouteRoute._addFileChildren(
    AuthenticatedUserRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedUserRouteRoute: typeof AuthenticatedUserRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedUserRouteRoute: AuthenticatedUserRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminGateRoute: AdminGateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
